import { createContext, useState, useEffect } from "react";
import { faker } from "@faker-js/faker";

let jsonObjectArray = [
  {
    FAAB: {
      icao: "FAAB",
      iata: "ALJ",
      name: "Alexander Bay Airport",
      city: "Alexander Bay",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 98,
      lat: -28.5750007629,
      lon: 16.5333003998,
      tz: "Africa/Johannesburg",
    },
    FAAD: {
      icao: "FAAD",
      iata: "",
      name: "Adelaide Airport",
      city: "Adelaide",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1955,
      lat: -32.6831016541,
      lon: 26.2942008972,
      tz: "Africa/Johannesburg",
    },
    FAAE: {
      icao: "FAAE",
      iata: "",
      name: "Aberdeen Airport",
      city: "Aberdeen",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2461,
      lat: -32.4667015076,
      lon: 24.0666999817,
      tz: "Africa/Johannesburg",
    },
    FAAF: {
      icao: "FAAF",
      iata: "",
      name: "Andrew's Field Airport",
      city: "Struisbaai",
      state: "Western-Cape",
      country: "ZA",
      elevation: 30,
      lat: -34.7628898621,
      lon: 20.0349159241,
      tz: "Africa/Johannesburg",
    },
    FAAG: {
      icao: "FAAG",
      iata: "AGZ",
      name: "Aggeneys Airport",
      city: "Aggeneys",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2648,
      lat: -29.2817993164,
      lon: 18.8138999939,
      tz: "Africa/Johannesburg",
    },
    FAAK: {
      icao: "FAAK",
      iata: "",
      name: "Askham Airport",
      city: "Askham",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2801,
      lat: -26.9869441986,
      lon: 20.7772216797,
      tz: "Africa/Johannesburg",
    },
    FAAL: {
      icao: "FAAL",
      iata: "ADY",
      name: "Alldays Airport",
      city: "Alldays",
      state: "Limpopo",
      country: "ZA",
      elevation: 2600,
      lat: -22.6790008545,
      lon: 29.0555000305,
      tz: "Africa/Johannesburg",
    },
    FAAM: {
      icao: "FAAM",
      iata: "",
      name: "Amsterdam Airport",
      city: "Amsterdam",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 4310,
      lat: -26.6333332062,
      lon: 30.6000003815,
      tz: "Africa/Johannesburg",
    },
    FAAN: {
      icao: "FAAN",
      iata: "",
      name: "Aliwal North Airport",
      city: "Aliwal North",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4405,
      lat: -30.6800003052,
      lon: 26.7299995422,
      tz: "Africa/Johannesburg",
    },
    FAAP: {
      icao: "FAAP",
      iata: "",
      name: "Aviators Paradise Field",
      city: "",
      state: "North-West",
      country: "ZA",
      elevation: 3800,
      lat: -25.69389,
      lon: 27.7825073972,
      tz: "Africa/Johannesburg",
    },
    FAAS: {
      icao: "FAAS",
      iata: "",
      name: "Ashton Airport",
      city: "Ashton",
      state: "Western-Cape",
      country: "ZA",
      elevation: 525,
      lat: -33.8166656494,
      lon: 20.0666675568,
      tz: "Africa/Johannesburg",
    },
    FABA: {
      icao: "FABA",
      iata: "",
      name: "Microland Flight Park",
      city: "Bapsfontein",
      state: "Gauteng",
      country: "ZA",
      elevation: 5476,
      lat: -25.9762557716,
      lon: 28.3890151978,
      tz: "Africa/Johannesburg",
    },
    FABB: {
      icao: "FABB",
      iata: "",
      name: "Brakpan Airport",
      city: "Brakpan",
      state: "Gauteng",
      country: "ZA",
      elevation: 5300,
      lat: -26.2385997772,
      lon: 28.3017997742,
      tz: "Africa/Johannesburg",
    },
    FABD: {
      icao: "FABD",
      iata: "",
      name: "Burghersdorp Airport",
      city: "Burgersdorp",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4734,
      lat: -30.9775009155,
      lon: 26.3080997467,
      tz: "Africa/Johannesburg",
    },
    FABE: {
      icao: "FABE",
      iata: "BIY",
      name: "Bisho Airport",
      city: "Bisho",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1950,
      lat: -32.8970985413,
      lon: 27.2791004181,
      tz: "Africa/Johannesburg",
    },
    FABF: {
      icao: "FABF",
      iata: "",
      name: "Barkley East Airport",
      city: "Barkley East",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 5940,
      lat: -30.9666671753,
      lon: 27.6041660309,
      tz: "Africa/Johannesburg",
    },
    FABG: {
      icao: "FABG",
      iata: "",
      name: "Buffelshoek Airport",
      city: "",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1347,
      lat: -24.702464,
      lon: 31.587875,
      tz: "Africa/Johannesburg",
    },
    FABH: {
      icao: "FABH",
      iata: "",
      name: "Belfast Aerodrome",
      city: "Belfast",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 6250,
      lat: -25.6587417378,
      lon: 30.041577816,
      tz: "Africa/Johannesburg",
    },
    FABK: {
      icao: "FABK",
      iata: "",
      name: "Bushmans Kloof Airport",
      city: "Bushman's Kloof",
      state: "Western-Cape",
      country: "ZA",
      elevation: 1050,
      lat: -32.035,
      lon: 19.0435,
      tz: "Africa/Johannesburg",
    },
    FABL: {
      icao: "FABL",
      iata: "BFN",
      name: "J B M Hertzog International Airport",
      city: "Bloemfontain",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4458,
      lat: -29.0926990509,
      lon: 26.302400589,
      tz: "Africa/Johannesburg",
    },
    FABM: {
      icao: "FABM",
      iata: "",
      name: "Bethlehem Airport",
      city: "Bethlehem",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5561,
      lat: -28.2483997345,
      lon: 28.3360996246,
      tz: "Africa/Johannesburg",
    },
    FABO: {
      icao: "FABO",
      iata: "",
      name: "Hendrik Potgieter Airport",
      city: "Bothaville",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4236,
      lat: -27.3668003082,
      lon: 26.6291999817,
      tz: "Africa/Johannesburg",
    },
    FABP: {
      icao: "FABP",
      iata: "",
      name: "Black Rock Airport",
      city: "Santoy",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3450,
      lat: -27.129724,
      lon: 22.846255,
      tz: "Africa/Johannesburg",
    },
    FABR: {
      icao: "FABR",
      iata: "",
      name: "Barberton Airport",
      city: "Umjindi (Barberton)",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 2250,
      lat: -25.7168687423,
      lon: 30.9751796722,
      tz: "Africa/Johannesburg",
    },
    FABS: {
      icao: "FABS",
      iata: "",
      name: "Brits Airport",
      city: "Brits",
      state: "North-West",
      country: "ZA",
      elevation: 3756,
      lat: -25.5323009491,
      lon: 27.7758998871,
      tz: "Africa/Johannesburg",
    },
    FABT: {
      icao: "FABT",
      iata: "",
      name: "Bethesda Road Airport",
      city: "Bethesda",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4630,
      lat: -31.8731994629,
      lon: 24.7968997955,
      tz: "Africa/Johannesburg",
    },
    FABU: {
      icao: "FABU",
      iata: "UTE",
      name: "Bultfontein Airport",
      city: "Bultfontein",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4400,
      lat: -28.273369,
      lon: 26.135835,
      tz: "Africa/Johannesburg",
    },
    FABV: {
      icao: "FABV",
      iata: "",
      name: "Brandviei Airport",
      city: "Brandviei",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2999,
      lat: -30.4666996002,
      lon: 20.4666996002,
      tz: "Africa/Johannesburg",
    },
    FABW: {
      icao: "FABW",
      iata: "",
      name: "Beaufort West Airport",
      city: "Beaufort West",
      state: "Western-Cape",
      country: "ZA",
      elevation: 2941,
      lat: -32.2999992371,
      lon: 22.6700000763,
      tz: "Africa/Johannesburg",
    },
    FABX: {
      icao: "FABX",
      iata: "",
      name: "Beatrix Airport",
      city: "Virginia",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4518,
      lat: -28.2450008392,
      lon: 26.771900177,
      tz: "Africa/Johannesburg",
    },
    FABZ: {
      icao: "FABZ",
      iata: "",
      name: "Bizana Airport",
      city: "Bizana",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2740,
      lat: -30.8603000641,
      lon: 29.863899231,
      tz: "Africa/Johannesburg",
    },
    FACA: {
      icao: "FACA",
      iata: "",
      name: "Monte Carlo Airport",
      city: "Monte Carlo",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4995,
      lat: -28.7999992371,
      lon: 27.4169998169,
      tz: "Africa/Johannesburg",
    },
    FACB: {
      icao: "FACB",
      iata: "",
      name: "Colesberg Airport",
      city: "Colesberg",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4639,
      lat: -30.7339000702,
      lon: 25.0650005341,
      tz: "Africa/Johannesburg",
    },
    FACC: {
      icao: "FACC",
      iata: "",
      name: "Arathusa Safari Lodge Airport",
      city: "Arathusa",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1200,
      lat: -24.7441673279,
      lon: 31.5224990845,
      tz: "Africa/Johannesburg",
    },
    FACD: {
      icao: "FACD",
      iata: "CDO",
      name: "Cradock Airport",
      city: "Cradock",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 3110,
      lat: -32.1567001343,
      lon: 25.6455993652,
      tz: "Africa/Johannesburg",
    },
    FACE: {
      icao: "FACE",
      iata: "",
      name: "Ceres Airport",
      city: "Ceres",
      state: "Western-Cape",
      country: "ZA",
      elevation: 1519,
      lat: -33.3530006409,
      lon: 19.3113994598,
      tz: "Africa/Johannesburg",
    },
    FACF: {
      icao: "FACF",
      iata: "",
      name: "Cap St Francis Airport",
      city: "St Francis",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 131,
      lat: -34.1869010925,
      lon: 24.8349990845,
      tz: "Africa/Johannesburg",
    },
    FACH: {
      icao: "FACH",
      iata: "",
      name: "Cookhouse Airport",
      city: "Cookhouse",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1893,
      lat: -32.7447013855,
      lon: 25.7963008881,
      tz: "Africa/Johannesburg",
    },
    FACI: {
      icao: "FACI",
      iata: "",
      name: "Citrusdal Airport",
      city: "Citrusdal",
      state: "Western-Cape",
      country: "ZA",
      elevation: 532,
      lat: -32.6176986694,
      lon: 19.005399704,
      tz: "Africa/Johannesburg",
    },
    FACK: {
      icao: "FACK",
      iata: "",
      name: "Christiana Airport",
      city: "Christiana",
      state: "North-West",
      country: "ZA",
      elevation: 3978,
      lat: -27.8777008057,
      lon: 25.2017993927,
      tz: "Africa/Johannesburg",
    },
    FACL: {
      icao: "FACL",
      iata: "",
      name: "Carolina Airport",
      city: "Carolina",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5420,
      lat: -26.0781002045,
      lon: 30.0925006866,
      tz: "Africa/Johannesburg",
    },
    FACN: {
      icao: "FACN",
      iata: "",
      name: "Carnarvon Airport",
      city: "Carnarvon",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4160,
      lat: -30.9885997772,
      lon: 22.1317005157,
      tz: "Africa/Johannesburg",
    },
    FACO: {
      icao: "FACO",
      iata: "",
      name: "Alkantpan Copper Airport",
      city: "Cooperton",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3589,
      lat: -29.9064006805,
      lon: 22.3166999817,
      tz: "Africa/Johannesburg",
    },
    FACR: {
      icao: "FACR",
      iata: "",
      name: "Carltonville Airport",
      city: "Carltonville",
      state: "Gauteng",
      country: "ZA",
      elevation: 5000,
      lat: -26.3666667938,
      lon: 27.3466663361,
      tz: "Africa/Johannesburg",
    },
    FACT: {
      icao: "FACT",
      iata: "CPT",
      name: "Cape Town International Airport",
      city: "Cape Town",
      state: "Western-Cape",
      country: "ZA",
      elevation: 151,
      lat: -33.9648017883,
      lon: 18.6016998291,
      tz: "Africa/Johannesburg",
    },
    FACV: {
      icao: "FACV",
      iata: "",
      name: "Calvinia Airport",
      city: "Calvinia",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3250,
      lat: -31.5002994537,
      lon: 19.72590065,
      tz: "Africa/Johannesburg",
    },
    FACW: {
      icao: "FACW",
      iata: "",
      name: "Clanwilliam Airport",
      city: "Clanwilliam",
      state: "Western-Cape",
      country: "ZA",
      elevation: 650,
      lat: -32.1831016541,
      lon: 18.8885993958,
      tz: "Africa/Johannesburg",
    },
    FACX: {
      icao: "FACX",
      iata: "",
      name: "Cathcart Airport",
      city: "Cathcart",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 3959,
      lat: -32.2871017456,
      lon: 27.1387996674,
      tz: "Africa/Johannesburg",
    },
    FACY: {
      icao: "FACY",
      iata: "",
      name: "Stilbaai Airport",
      city: "Stilbaai",
      state: "Western-Cape",
      country: "ZA",
      elevation: 266,
      lat: -34.3517990112,
      lon: 21.4248008728,
      tz: "Africa/Johannesburg",
    },
    FADA: {
      icao: "FADA",
      iata: "",
      name: "De Aar Airport",
      city: "De Aar",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4154,
      lat: -30.692199707,
      lon: 24.0205993652,
      tz: "Africa/Johannesburg",
    },
    FADB: {
      icao: "FADB",
      iata: "",
      name: "Dwaalboom Airport",
      city: "Dwaalboom",
      state: "Limpopo",
      country: "ZA",
      elevation: 3652,
      lat: -24.8071994781,
      lon: 26.82970047,
      tz: "Africa/Johannesburg",
    },
    FADD: {
      icao: "FADD",
      iata: "",
      name: "Dundee Airport",
      city: "Dundee",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4219,
      lat: -28.1830997467,
      lon: 30.2224998474,
      tz: "Africa/Johannesburg",
    },
    FADE: {
      icao: "FADE",
      iata: "",
      name: "Delmas Airport",
      city: "Delmas",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5075,
      lat: -26.1416664124,
      lon: 28.6916675568,
      tz: "Africa/Johannesburg",
    },
    FADG: {
      icao: "FADG",
      iata: "",
      name: "Dordrecht Airport",
      city: "Dordrecht",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 5200,
      lat: -31.3833332062,
      lon: 27.0333328247,
      tz: "Africa/Johannesburg",
    },
    FADH: {
      icao: "FADH",
      iata: "",
      name: "Durnacol Airport",
      city: "Durnacol",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4317,
      lat: -28.0461006165,
      lon: 30.0063991547,
      tz: "Africa/Johannesburg",
    },
    FADK: {
      icao: "FADK",
      iata: "DUK",
      name: "Mubatuba Airport",
      city: "Mubatuba",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 210,
      lat: -28.3684005737,
      lon: 32.2481002808,
      tz: "Africa/Johannesburg",
    },
    FADL: {
      icao: "FADL",
      iata: "",
      name: "Delareyville Airport",
      city: "Delareyville",
      state: "North-West",
      country: "ZA",
      elevation: 4469,
      lat: -26.6791992188,
      lon: 25.4747009277,
      tz: "Africa/Johannesburg",
    },
    FADM: {
      icao: "FADM",
      iata: "",
      name: "Kokstad Airport",
      city: "Kokstad",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4084,
      lat: -30.5564994812,
      lon: 29.4081993103,
      tz: "Africa/Johannesburg",
    },
    FADN: {
      icao: "FADN",
      iata: "",
      name: "Durban International Airport",
      city: "Durban",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 33,
      lat: -29.9701004028,
      lon: 30.9505004883,
      tz: "Africa/Johannesburg",
    },
    FADO: {
      icao: "FADO",
      iata: "",
      name: "Dendron Airport",
      city: "Dendron",
      state: "Limpopo",
      country: "ZA",
      elevation: 3399,
      lat: -23.3805999756,
      lon: 29.3208007813,
      tz: "Africa/Johannesburg",
    },
    FADP: {
      icao: "FADP",
      iata: "",
      name: "Darlington Dam Lodge Airport",
      city: "Port Elizabeth",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 847,
      lat: -33.1832008362,
      lon: 25.1931991577,
      tz: "Africa/Johannesburg",
    },
    FADQ: {
      icao: "FADQ",
      iata: "PZL",
      name: "Zulu Inyala Airport",
      city: "Phinda",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 160,
      lat: -27.8493995667,
      lon: 32.3097000122,
      tz: "Africa/Johannesburg",
    },
    FADR: {
      icao: "FADR",
      iata: "",
      name: "Dunnottar Airport",
      city: "Dunnottar",
      state: "Gauteng",
      country: "ZA",
      elevation: 5241,
      lat: -26.3497009277,
      lon: 28.4419002533,
      tz: "Africa/Johannesburg",
    },
    FADS: {
      icao: "FADS",
      iata: "",
      name: "De Doorns Airport",
      city: "De Doorns",
      state: "Western-Cape",
      country: "ZA",
      elevation: 1626,
      lat: -33.455557,
      lon: 19.684493,
      tz: "Africa/Johannesburg",
    },
    FADU: {
      icao: "FADU",
      iata: "",
      name: "Walkersons Field",
      city: "",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 6041,
      lat: -25.36278,
      lon: 30.18778,
      tz: "Africa/Johannesburg",
    },
    FADV: {
      icao: "FADV",
      iata: "",
      name: "Devon Airport",
      city: "Devon",
      state: "Gauteng",
      country: "ZA",
      elevation: 5460,
      lat: -26.3589992523,
      lon: 28.7896995544,
      tz: "Africa/Johannesburg",
    },
    FADX: {
      icao: "FADX",
      iata: "",
      name: "Delta 200 Airstrip",
      city: "Koeberg",
      state: "Western-Cape",
      country: "ZA",
      elevation: 220,
      lat: -33.6494935368,
      lon: 18.4718799591,
      tz: "Africa/Johannesburg",
    },
    FADY: {
      icao: "FADY",
      iata: "",
      name: "De Aar Military Airport",
      city: "De Aar",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4037,
      lat: -30.6365089417,
      lon: 23.9197254181,
      tz: "Africa/Johannesburg",
    },
    FADZ: {
      icao: "FADZ",
      iata: "",
      name: "Drakensberg Gardens Airport",
      city: "Drakensberg Gardens",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 5948,
      lat: -29.75,
      lon: 29.25,
      tz: "Africa/Johannesburg",
    },
    FAEC: {
      icao: "FAEC",
      iata: "",
      name: "Estcourt Airport",
      city: "Estcourt",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4262,
      lat: -29.0471992493,
      lon: 29.9106006622,
      tz: "Africa/Johannesburg",
    },
    FAED: {
      icao: "FAED",
      iata: "",
      name: "Edenburg Airport",
      city: "Edenburg",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4509,
      lat: -29.75,
      lon: 25.8999996185,
      tz: "Africa/Johannesburg",
    },
    FAEG: {
      icao: "FAEG",
      iata: "",
      name: "Egnep Airport",
      city: "Egnep",
      state: "Limpopo",
      country: "ZA",
      elevation: 2299,
      lat: -24.5669994354,
      lon: 30.3169994354,
      tz: "Africa/Johannesburg",
    },
    FAEL: {
      icao: "FAEL",
      iata: "ELS",
      name: "Ben Schoeman Airport",
      city: "East London",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 435,
      lat: -33.0355987549,
      lon: 27.8258991241,
      tz: "Africa/Johannesburg",
    },
    FAEM: {
      icao: "FAEM",
      iata: "EMG",
      name: "Empangeni Airport",
      city: "Empangeni",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 251,
      lat: -28.7199993134,
      lon: 31.8899993896,
      tz: "Africa/Johannesburg",
    },
    FAEO: {
      icao: "FAEO",
      iata: "",
      name: "Ermelo Airport",
      city: "Ermelo",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5700,
      lat: -26.4955997467,
      lon: 29.9797992706,
      tz: "Africa/Johannesburg",
    },
    FAER: {
      icao: "FAER",
      iata: "ELL",
      name: "Ellisras Matimba Airport",
      city: "Ellisras",
      state: "Limpopo",
      country: "ZA",
      elevation: 2799,
      lat: -23.7266998291,
      lon: 27.6882991791,
      tz: "Africa/Johannesburg",
    },
    FAES: {
      icao: "FAES",
      iata: "",
      name: "Eshowe Airport",
      city: "Eshowe",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 1601,
      lat: -28.8801994324,
      lon: 31.4549007416,
      tz: "Africa/Johannesburg",
    },
    FAET: {
      icao: "FAET",
      iata: "",
      name: "Elliot Airport",
      city: "Elliot",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 5028,
      lat: -31.3069000244,
      lon: 27.8495006561,
      tz: "Africa/Johannesburg",
    },
    FAFB: {
      icao: "FAFB",
      iata: "FCB",
      name: "Ficksburg Sentraoes Airport",
      city: "Ficksburg",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5315,
      lat: -28.8230991364,
      lon: 27.9088993073,
      tz: "Africa/Johannesburg",
    },
    FAFF: {
      icao: "FAFF",
      iata: "",
      name: "Frankfort Airport",
      city: "Frankfort",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5176,
      lat: -27.2854003906,
      lon: 28.5153007507,
      tz: "Africa/Johannesburg",
    },
    FAFG: {
      icao: "FAFG",
      iata: "",
      name: "Flamingo Vlei Airport",
      city: "Flamingo Vlei",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3248,
      lat: -30.4909992218,
      lon: 21.1217002869,
      tz: "Africa/Johannesburg",
    },
    FAFK: {
      icao: "FAFK",
      iata: "",
      name: "Fisantekraal Airport",
      city: "Fisantekraal",
      state: "Western-Cape",
      country: "ZA",
      elevation: 410,
      lat: -33.7700004578,
      lon: 18.7399997711,
      tz: "Africa/Johannesburg",
    },
    FAFO: {
      icao: "FAFO",
      iata: "",
      name: "Fort Beaufort Airport",
      city: "Fort Beaufort",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1581,
      lat: -32.7905006409,
      lon: 26.5776996613,
      tz: "Africa/Johannesburg",
    },
    FAFR: {
      icao: "FAFR",
      iata: "",
      name: "Fraserburg Airport",
      city: "Fraseburg",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4180,
      lat: -31.9339008331,
      lon: 21.5025005341,
      tz: "Africa/Johannesburg",
    },
    FAFU: {
      icao: "FAFU",
      iata: "",
      name: "Fraaiuitzicht Airport",
      city: "Fraaiuitzicht",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4841,
      lat: -27.3169994354,
      lon: 27.25,
      tz: "Africa/Johannesburg",
    },
    FAFW: {
      icao: "FAFW",
      iata: "",
      name: "Freeway Airport",
      city: "Kromdraai",
      state: "Gauteng",
      country: "ZA",
      elevation: 3819,
      lat: -25.4771995544,
      lon: 28.2900009155,
      tz: "Africa/Johannesburg",
    },
    FAGA: {
      icao: "FAGA",
      iata: "",
      name: "Grange Airport",
      city: "Umzimkulu",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2600,
      lat: -30.2670001984,
      lon: 29.966999054,
      tz: "Africa/Johannesburg",
    },
    FAGC: {
      icao: "FAGC",
      iata: "GCJ",
      name: "Grand Central Airport",
      city: "Midrand",
      state: "Gauteng",
      country: "ZA",
      elevation: 5325,
      lat: -25.9862995148,
      lon: 28.1401004791,
      tz: "Africa/Johannesburg",
    },
    FAGG: {
      icao: "FAGG",
      iata: "GRJ",
      name: "George Airport",
      city: "George",
      state: "Western-Cape",
      country: "ZA",
      elevation: 648,
      lat: -34.0055999756,
      lon: 22.378900528,
      tz: "Africa/Johannesburg",
    },
    FAGH: {
      icao: "FAGH",
      iata: "",
      name: "Glen Grey Airport",
      city: "Emmaus",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3500,
      lat: -28.8333339691,
      lon: 29.4666671753,
      tz: "Africa/Johannesburg",
    },
    FAGI: {
      icao: "FAGI",
      iata: "GIY",
      name: "Giyani Airport",
      city: "Giyani",
      state: "Limpopo",
      country: "ZA",
      elevation: 1584,
      lat: -23.2833003998,
      lon: 30.6499996185,
      tz: "Africa/Johannesburg",
    },
    FAGJ: {
      icao: "FAGJ",
      iata: "",
      name: "Gifvlei Airport",
      city: "Gifvlei",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3199,
      lat: -30.3833007813,
      lon: 20.0333003998,
      tz: "Africa/Johannesburg",
    },
    FAGL: {
      icao: "FAGL",
      iata: "",
      name: "Groblersdal Kob Airport",
      city: "Groblersdal",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 3051,
      lat: -25.1868991852,
      lon: 29.4032993317,
      tz: "Africa/Johannesburg",
    },
    FAGM: {
      icao: "FAGM",
      iata: "QRA",
      name: "Rand Airport",
      city: "Johannesburg",
      state: "Gauteng",
      country: "ZA",
      elevation: 5483,
      lat: -26.2425003052,
      lon: 28.1511993408,
      tz: "Africa/Johannesburg",
    },
    FAGO: {
      icao: "FAGO",
      iata: "",
      name: "Gowrie Airport",
      city: "",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1200,
      lat: -24.7371653036,
      lon: 31.5602874756,
      tz: "Africa/Johannesburg",
    },
    FAGR: {
      icao: "FAGR",
      iata: "",
      name: "Graaff Reinet Airport",
      city: "Graaff-Reinet",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2604,
      lat: -32.1935997009,
      lon: 24.5414009094,
      tz: "Africa/Johannesburg",
    },
    FAGS: {
      icao: "FAGS",
      iata: "",
      name: "Giants Castle Airport",
      city: "Giant'S Castle Game Reserve",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 6086,
      lat: -29.2696990967,
      lon: 29.5660991669,
      tz: "Africa/Johannesburg",
    },
    FAGT: {
      icao: "FAGT",
      iata: "",
      name: "Grahamstown Airport",
      city: "Grahamstown",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2135,
      lat: -33.2846984863,
      lon: 26.4981002808,
      tz: "Africa/Johannesburg",
    },
    FAGV: {
      icao: "FAGV",
      iata: "",
      name: "Gravelotte Airport",
      city: "Gravelotte",
      state: "Limpopo",
      country: "ZA",
      elevation: 1650,
      lat: -23.9167003632,
      lon: 30.7000007629,
      tz: "Africa/Johannesburg",
    },
    FAGW: {
      icao: "FAGW",
      iata: "",
      name: "Magwa Airport",
      city: "Magwa",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1823,
      lat: -31.3939418793,
      lon: 29.6934700012,
      tz: "Africa/Johannesburg",
    },
    FAGY: {
      icao: "FAGY",
      iata: "",
      name: "Greytown Airport",
      city: "Greytown",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3531,
      lat: -29.1219997406,
      lon: 30.5867004395,
      tz: "Africa/Johannesburg",
    },
    FAHA: {
      icao: "FAHA",
      iata: "",
      name: "Harmony Airport",
      city: "Virginia",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4399,
      lat: -28.0786991119,
      lon: 26.8612003326,
      tz: "Africa/Johannesburg",
    },
    FAHB: {
      icao: "FAHB",
      iata: "",
      name: "Hartebeespoortdam Airport",
      city: "Hartebeespoort",
      state: "Limpopo",
      country: "ZA",
      elevation: 3740,
      lat: -24.5023994446,
      lon: 28.0790996552,
      tz: "Africa/Johannesburg",
    },
    FAHC: {
      icao: "FAHC",
      iata: "",
      name: "Howick Airport",
      city: "Howick",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3619,
      lat: -29.5527992249,
      lon: 30.2110996246,
      tz: "Africa/Johannesburg",
    },
    FAHD: {
      icao: "FAHD",
      iata: "",
      name: "Humansdorp Airport",
      city: "Humansdorp",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 345,
      lat: -34.0365982056,
      lon: 24.7889003754,
      tz: "Africa/Johannesburg",
    },
    FAHE: {
      icao: "FAHE",
      iata: "",
      name: "Pullenshope Hendrina Airport",
      city: "Hendrina",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5171,
      lat: -25.9778003693,
      lon: 29.6189002991,
      tz: "Africa/Johannesburg",
    },
    FAHF: {
      icao: "FAHF",
      iata: "",
      name: "Henrys Flats Airport",
      city: "Henry'S Flats",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1709,
      lat: -33.0461006165,
      lon: 25.7168998718,
      tz: "Africa/Johannesburg",
    },
    FAHG: {
      icao: "FAHG",
      iata: "",
      name: "Heidelburg Airport",
      city: "Heidelburg",
      state: "Gauteng",
      country: "ZA",
      elevation: 5089,
      lat: -26.5100002289,
      lon: 28.3899993896,
      tz: "Africa/Johannesburg",
    },
    FAHH: {
      icao: "FAHH",
      iata: "",
      name: "Hibberdene Airport",
      city: "Hibberdene",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 89,
      lat: -30.6299991608,
      lon: 30.5200004578,
      tz: "Africa/Johannesburg",
    },
    FAHI: {
      icao: "FAHI",
      iata: "",
      name: "Halfweg Airport",
      city: "Halfweg",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3159,
      lat: -30.013299942,
      lon: 20.1392002106,
      tz: "Africa/Johannesburg",
    },
    FAHJ: {
      icao: "FAHJ",
      iata: "",
      name: "Harding Airport",
      city: "Harding",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2890,
      lat: -30.5666999817,
      lon: 29.8833007813,
      tz: "Africa/Johannesburg",
    },
    FAHK: {
      icao: "FAHK",
      iata: "",
      name: "Haakdoornboom Airport",
      city: "Haakdoornboom",
      state: "Gauteng",
      country: "ZA",
      elevation: 4055,
      lat: -25.5872001648,
      lon: 28.1158008575,
      tz: "Africa/Johannesburg",
    },
    FAHL: {
      icao: "FAHL",
      iata: "HLW",
      name: "Hluhluwe Airport",
      city: "Hluhluwe",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 249,
      lat: -28.0166049887,
      lon: 32.2751712799,
      tz: "Africa/Johannesburg",
    },
    FAHO: {
      icao: "FAHO",
      iata: "",
      name: "Heilbron Airport",
      city: "Heilbron",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5200,
      lat: -27.2786006927,
      lon: 27.9955997467,
      tz: "Africa/Johannesburg",
    },
    FAHP: {
      icao: "FAHP",
      iata: "",
      name: "Hoopstad Airport",
      city: "Hoopstad",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4131,
      lat: -27.8216991425,
      lon: 25.9169006348,
      tz: "Africa/Johannesburg",
    },
    FAHR: {
      icao: "FAHR",
      iata: "HRS",
      name: "Harrismith Airport",
      city: "Harrismith",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5585,
      lat: -28.2350997925,
      lon: 29.1061992645,
      tz: "Africa/Johannesburg",
    },
    FAHS: {
      icao: "FAHS",
      iata: "HDS",
      name: "Hoedspruit Air Force Base Airport",
      city: "Hoedspruit",
      state: "Limpopo",
      country: "ZA",
      elevation: 1743,
      lat: -24.3686008453,
      lon: 31.0487003326,
      tz: "Africa/Johannesburg",
    },
    FAHT: {
      icao: "FAHT",
      iata: "",
      name: "Hoedspruit Airport",
      city: "Hoedspruit",
      state: "Limpopo",
      country: "ZA",
      elevation: 1801,
      lat: -24.3516998291,
      lon: 30.9493999481,
      tz: "Africa/Johannesburg",
    },
    FAHU: {
      icao: "FAHU",
      iata: "",
      name: "H M S Bastard Memorial Airport",
      city: "H.M.S.Bastard Memorial",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4701,
      lat: -30.5424995422,
      lon: 29.4990005493,
      tz: "Africa/Johannesburg",
    },
    FAHV: {
      icao: "FAHV",
      iata: "",
      name: "Gariep Dam Airport",
      city: "Hendrik Verwoerd dam",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4176,
      lat: -30.5622005463,
      lon: 25.5282993317,
      tz: "Africa/Johannesburg",
    },
    FAIA: {
      icao: "FAIA",
      iata: "",
      name: "Itala Airport",
      city: "Itala",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2665,
      lat: -27.486700058,
      lon: 31.1711006165,
      tz: "Africa/Johannesburg",
    },
    FAID: {
      icao: "FAID",
      iata: "",
      name: "Idutywa Airport",
      city: "Idutywa",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2530,
      lat: -32.0999984741,
      lon: 28.3166999817,
      tz: "Africa/Johannesburg",
    },
    FAIO: {
      icao: "FAIO",
      iata: "",
      name: "Odi Airport",
      city: "Lerulaneng",
      state: "North-West",
      country: "ZA",
      elevation: 3862,
      lat: -25.5499992371,
      lon: 27.9330005646,
      tz: "Africa/Johannesburg",
    },
    FAIS: {
      icao: "FAIS",
      iata: "",
      name: "Isithebe Airport",
      city: "Nyoni",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 313,
      lat: -29.105556488,
      lon: 31.4074993134,
      tz: "Africa/Johannesburg",
    },
    FAIV: {
      icao: "FAIV",
      iata: "",
      name: "Ingwavuma Airport",
      city: "Ingwavuma",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2100,
      lat: -27.117099762,
      lon: 32.0087013245,
      tz: "Africa/Johannesburg",
    },
    FAIW: {
      icao: "FAIW",
      iata: "",
      name: "Indwe Airport",
      city: "Indwe",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4167,
      lat: -31.4833335876,
      lon: 27.3500003815,
      tz: "Africa/Johannesburg",
    },
    FAJF: {
      icao: "FAJF",
      iata: "",
      name: "Jagersfontain Airport",
      city: "Jagersfontain",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4714,
      lat: -29.7625007629,
      lon: 25.4330005646,
      tz: "Africa/Johannesburg",
    },
    FAJP: {
      icao: "FAJP",
      iata: "",
      name: "Joubertina Airport",
      city: "Joubertina",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2007,
      lat: -33.831199646,
      lon: 23.8300991058,
      tz: "Africa/Johannesburg",
    },
    FAJV: {
      icao: "FAJV",
      iata: "",
      name: "Jansenville Airport",
      city: "Jansenville",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1430,
      lat: -32.9390983582,
      lon: 24.6707000732,
      tz: "Africa/Johannesburg",
    },
    FAKA: {
      icao: "FAKA",
      iata: "",
      name: "Kagga Kamma Airport",
      city: "Kagga Kamma Private Game Reserve",
      state: "Western-Cape",
      country: "ZA",
      elevation: 3494,
      lat: -32.7469940186,
      lon: 19.5620994568,
      tz: "Africa/Johannesburg",
    },
    FAKB: {
      icao: "FAKB",
      iata: "",
      name: "Kosibaai Airport",
      city: "Kosi Bay",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 140,
      lat: -27.0333328247,
      lon: 32.75,
      tz: "Africa/Johannesburg",
    },
    FAKD: {
      icao: "FAKD",
      iata: "KXE",
      name: "P C Pelser Airport",
      city: "Klerksdorp",
      state: "North-West",
      country: "ZA",
      elevation: 4444,
      lat: -26.871099472,
      lon: 26.718000412,
      tz: "Africa/Johannesburg",
    },
    FAKE: {
      icao: "FAKE",
      iata: "",
      name: "Keimouth Airport",
      city: "Keimouth",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 222,
      lat: -32.7000007629,
      lon: 28.3500003815,
      tz: "Africa/Johannesburg",
    },
    FAKF: {
      icao: "FAKF",
      iata: "",
      name: "Koffee Bay Airport",
      city: "Koffee Bay",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 10,
      lat: -31.9638996124,
      lon: 29.14909935,
      tz: "Africa/Johannesburg",
    },
    FAKG: {
      icao: "FAKG",
      iata: "",
      name: "Komati Power Station Airport",
      city: "Komati Power Station",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5289,
      lat: -26.0932998657,
      lon: 29.4556007385,
      tz: "Africa/Johannesburg",
    },
    FAKH: {
      icao: "FAKH",
      iata: "",
      name: "Kenhardt Airport",
      city: "Kenhardt",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2723,
      lat: -29.3267002106,
      lon: 21.1886005402,
      tz: "Africa/Johannesburg",
    },
    FAKI: {
      icao: "FAKI",
      iata: "",
      name: "Kobb Inn Airport",
      city: "Kobb Inn",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 147,
      lat: -32.433799,
      lon: 28.683467,
      tz: "Africa/Johannesburg",
    },
    FAKK: {
      icao: "FAKK",
      iata: "",
      name: "Kakamas Airport",
      city: "Kakamas",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2322,
      lat: -28.7999992371,
      lon: 20.6329994202,
      tz: "Africa/Johannesburg",
    },
    FAKL: {
      icao: "FAKL",
      iata: "",
      name: "Kriel Airport",
      city: "Kriel",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5262,
      lat: -26.2511005402,
      lon: 29.1947002411,
      tz: "Africa/Johannesburg",
    },
    FAKM: {
      icao: "FAKM",
      iata: "KIM",
      name: "Kimberley Airport",
      city: "Kimberley",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3950,
      lat: -28.8027992249,
      lon: 24.7651996613,
      tz: "Africa/Johannesburg",
    },
    FAKN: {
      icao: "FAKN",
      iata: "MQP",
      name: "Kruger Mpumalanga International Airport",
      city: "Mpumalanga",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 2829,
      lat: -25.3831996918,
      lon: 31.1056003571,
      tz: "Africa/Johannesburg",
    },
    FAKO: {
      icao: "FAKO",
      iata: "",
      name: "Komga Airport",
      city: "Komga",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2178,
      lat: -32.5928001404,
      lon: 27.8757991791,
      tz: "Africa/Johannesburg",
    },
    FAKP: {
      icao: "FAKP",
      iata: "KOF",
      name: "Komatipoort Airport",
      city: "Komatipoort",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 541,
      lat: -25.4402999878,
      lon: 31.9300003052,
      tz: "Africa/Johannesburg",
    },
    FAKR: {
      icao: "FAKR",
      iata: "",
      name: "Krugersdorp Airport",
      city: "Krugersdorp",
      state: "Gauteng",
      country: "ZA",
      elevation: 5499,
      lat: -26.0809993744,
      lon: 27.7257003784,
      tz: "Africa/Johannesburg",
    },
    FAKS: {
      icao: "FAKS",
      iata: "",
      name: "Kroonstad Airport",
      city: "Kroonstad",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4700,
      lat: -27.6606006622,
      lon: 27.3157997131,
      tz: "Africa/Johannesburg",
    },
    FAKT: {
      icao: "FAKT",
      iata: "",
      name: "Kitty Hawk Airport",
      city: "Boschkop",
      state: "Gauteng",
      country: "ZA",
      elevation: 4619,
      lat: -25.8600006104,
      lon: 28.4500007629,
      tz: "Africa/Johannesburg",
    },
    FAKU: {
      icao: "FAKU",
      iata: "KMH",
      name: "Johan Pienaar Airport",
      city: "Kuruman",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4382,
      lat: -27.4566993713,
      lon: 23.4113998413,
      tz: "Africa/Johannesburg",
    },
    FAKV: {
      icao: "FAKV",
      iata: "",
      name: "Koffyfontein Min Airport",
      city: "Koffyfontein",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 3996,
      lat: -29.4393997192,
      lon: 24.9885997772,
      tz: "Africa/Johannesburg",
    },
    FAKW: {
      icao: "FAKW",
      iata: "",
      name: "Kareedouw Airport",
      city: "Kareedouw",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1050,
      lat: -33.9666671753,
      lon: 24.2999992371,
      tz: "Africa/Johannesburg",
    },
    FAKX: {
      icao: "FAKX",
      iata: "",
      name: "Kenton on Sea Airport",
      city: "Kenton On Sea",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 172,
      lat: -33.6693000793,
      lon: 26.6308994293,
      tz: "Africa/Johannesburg",
    },
    FAKZ: {
      icao: "FAKZ",
      iata: "KLZ",
      name: "Kleinsee Airport",
      city: "Kleinsee",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 270,
      lat: -29.6884002686,
      lon: 17.0939998627,
      tz: "Africa/Johannesburg",
    },
    FALA: {
      icao: "FALA",
      iata: "HLA",
      name: "Lanseria Airport",
      city: "Johannesburg",
      state: "Gauteng",
      country: "ZA",
      elevation: 4517,
      lat: -25.9384994507,
      lon: 27.9260997772,
      tz: "Africa/Johannesburg",
    },
    FALB: {
      icao: "FALB",
      iata: "",
      name: "Ladybrand Af Airport",
      city: "Ladybrand",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5180,
      lat: -29.1811008453,
      lon: 27.4535999298,
      tz: "Africa/Johannesburg",
    },
    FALC: {
      icao: "FALC",
      iata: "LMR",
      name: "Lime Acres Finsch Mine Airport",
      city: "Lime Acres",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4900,
      lat: -28.3600997925,
      lon: 23.4391002655,
      tz: "Africa/Johannesburg",
    },
    FALD: {
      icao: "FALD",
      iata: "LDZ",
      name: "Londolozi Airport",
      city: "Londolozi",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1300,
      lat: -24.7502002716,
      lon: 31.4757003784,
      tz: "Africa/Johannesburg",
    },
    FALE: {
      icao: "FALE",
      iata: "DUR",
      name: "King Shaka International Airport",
      city: "Durban",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 295,
      lat: -29.6144444444,
      lon: 31.1197222222,
      tz: "Africa/Johannesburg",
    },
    FALF: {
      icao: "FALF",
      iata: "",
      name: "Loeriesfontein Airport",
      city: "Loeriesfontein",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2997,
      lat: -30.9064006805,
      lon: 19.4253005981,
      tz: "Africa/Johannesburg",
    },
    FALH: {
      icao: "FALH",
      iata: "",
      name: "Lohathla Military Airport",
      city: "Lohathla",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4500,
      lat: -28.0368003845,
      lon: 23.0986995697,
      tz: "Africa/Johannesburg",
    },
    FALI: {
      icao: "FALI",
      iata: "",
      name: "Lichtenburg Airport",
      city: "Lichtenburg",
      state: "North-West",
      country: "ZA",
      elevation: 4875,
      lat: -26.175699234,
      lon: 26.1846008301,
      tz: "Africa/Johannesburg",
    },
    FALK: {
      icao: "FALK",
      iata: "LUJ",
      name: "Lusikisiki Airport",
      city: "Lusikisiki",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1831,
      lat: -31.3666992188,
      lon: 29.5832996368,
      tz: "Africa/Johannesburg",
    },
    FALL: {
      icao: "FALL",
      iata: "",
      name: "Lydenburg Airport",
      city: "Lydenburg",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 4882,
      lat: -25.1033000946,
      lon: 30.4141998291,
      tz: "Africa/Johannesburg",
    },
    FALM: {
      icao: "FALM",
      iata: "",
      name: "Makhado Air Force Base Airport",
      city: "Louis Trichardt Southwest",
      state: "Limpopo",
      country: "ZA",
      elevation: 3069,
      lat: -23.1599006653,
      lon: 29.6965007782,
      tz: "Africa/Johannesburg",
    },
    FALO: {
      icao: "FALO",
      iata: "LCD",
      name: "Louis Trichardt Airport",
      city: "Louis Trichardt",
      state: "Limpopo",
      country: "ZA",
      elevation: 3025,
      lat: -23.0618991852,
      lon: 29.8647003174,
      tz: "Africa/Johannesburg",
    },
    FALQ: {
      icao: "FALQ",
      iata: "",
      name: "El Mirador Airport",
      city: "Ardmore",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3897,
      lat: -28.9861106873,
      lon: 29.4797229767,
      tz: "Africa/Johannesburg",
    },
    FALR: {
      icao: "FALR",
      iata: "",
      name: "Steytlerville Airport",
      city: "Steytlerville",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1450,
      lat: -33.3370018005,
      lon: 24.3213996887,
      tz: "Africa/Johannesburg",
    },
    FALS: {
      icao: "FALS",
      iata: "",
      name: "Somersveld Airport",
      city: "Somersveld",
      state: "Western-Cape",
      country: "ZA",
      elevation: 196,
      lat: -33.2462272644,
      lon: 18.4799976349,
      tz: "Africa/Johannesburg",
    },
    FALW: {
      icao: "FALW",
      iata: "SDB",
      name: "Langebaanweg Airport",
      city: "Langebaanweg",
      state: "Western-Cape",
      country: "ZA",
      elevation: 108,
      lat: -32.9688987732,
      lon: 18.1602993011,
      tz: "Africa/Johannesburg",
    },
    FALY: {
      icao: "FALY",
      iata: "LAY",
      name: "Ladysmith Airport",
      city: "Ladysmith",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3548,
      lat: -28.5816993713,
      lon: 29.7497005463,
      tz: "Africa/Johannesburg",
    },
    FAMA: {
      icao: "FAMA",
      iata: "",
      name: "Matatiele Airport",
      city: "Matatiele",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4762,
      lat: -30.3222007751,
      lon: 28.7942008972,
      tz: "Africa/Johannesburg",
    },
    FAMB: {
      icao: "FAMB",
      iata: "",
      name: "Middelburg Airport",
      city: "Middelburg",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 4886,
      lat: -25.6847991943,
      lon: 29.4402008057,
      tz: "Africa/Johannesburg",
    },
    FAMC: {
      icao: "FAMC",
      iata: "",
      name: "Middelburg 2 Airport",
      city: "Cape Town",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4022,
      lat: -31.5471992493,
      lon: 25.0293998718,
      tz: "Africa/Johannesburg",
    },
    FAMD: {
      icao: "FAMD",
      iata: "AAM",
      name: "Malamala Airport",
      city: "Malamala",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1124,
      lat: -24.8180999756,
      lon: 31.5445995331,
      tz: "Africa/Johannesburg",
    },
    FAMF: {
      icao: "FAMF",
      iata: "",
      name: "Malabar Airport",
      city: "Malabar",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3348,
      lat: -29.0118999481,
      lon: 23.8474006653,
      tz: "Africa/Johannesburg",
    },
    FAMG: {
      icao: "FAMG",
      iata: "MGH",
      name: "Margate Airport",
      city: "Margate",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 495,
      lat: -30.8574008942,
      lon: 30.343000412,
      tz: "Africa/Johannesburg",
    },
    FAMH: {
      icao: "FAMH",
      iata: "MEZ",
      name: "Musina(Messina) Airport",
      city: "Musina",
      state: "Limpopo",
      country: "ZA",
      elevation: 1904,
      lat: -22.3560009003,
      lon: 29.9862003326,
      tz: "Africa/Johannesburg",
    },
    FAMI: {
      icao: "FAMI",
      iata: "",
      name: "Marble Hall Airport",
      city: "Marble Hall",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 2980,
      lat: -24.9890995026,
      lon: 29.2831001282,
      tz: "Africa/Johannesburg",
    },
    FAMJ: {
      icao: "FAMJ",
      iata: "",
      name: "Majuba Power Station Airport",
      city: "Amerspoort",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5600,
      lat: -27.0792999268,
      lon: 29.7784996033,
      tz: "Africa/Johannesburg",
    },
    FAMK: {
      icao: "FAMK",
      iata: "",
      name: "Mafeking Airport",
      city: "Mafeking",
      state: "North-West",
      country: "ZA",
      elevation: 4201,
      lat: -25.8166675568,
      lon: 25.6166667938,
      tz: "Africa/Johannesburg",
    },
    FAML: {
      icao: "FAML",
      iata: "",
      name: "Manyani Game Lodge Airport",
      city: "Mafeking",
      state: "North-West",
      country: "ZA",
      elevation: 4383,
      lat: -25.8166999817,
      lon: 25.7166996002,
      tz: "Africa/Johannesburg",
    },
    FAMM: {
      icao: "FAMM",
      iata: "MBD",
      name: "Mmabatho International Airport",
      city: "Mafeking",
      state: "North-West",
      country: "ZA",
      elevation: 4181,
      lat: -25.7984008789,
      lon: 25.5480003357,
      tz: "Africa/Johannesburg",
    },
    FAMN: {
      icao: "FAMN",
      iata: "LLE",
      name: "Riverside Airport",
      city: "Malelane",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1024,
      lat: -25.4300003052,
      lon: 31.5767002106,
      tz: "Africa/Johannesburg",
    },
    FAMO: {
      icao: "FAMO",
      iata: "MZY",
      name: "Mossel Bay Airport",
      city: "Mossel Bay",
      state: "Western-Cape",
      country: "ZA",
      elevation: 531,
      lat: -34.1582984924,
      lon: 22.058599472,
      tz: "Africa/Johannesburg",
    },
    FAMP: {
      icao: "FAMP",
      iata: "",
      name: "Madimbo Airport",
      city: "Matshakatini",
      state: "Limpopo",
      country: "ZA",
      elevation: 2116,
      lat: -22.3747005463,
      lon: 30.8815994263,
      tz: "Africa/Johannesburg",
    },
    FAMQ: {
      icao: "FAMQ",
      iata: "",
      name: "Maclear Airport",
      city: "Maclear",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4106,
      lat: -31.0832996368,
      lon: 28.3763999939,
      tz: "Africa/Johannesburg",
    },
    FAMS: {
      icao: "FAMS",
      iata: "",
      name: "Morningside Farm Airport",
      city: "Silveroaks",
      state: "North-West",
      country: "ZA",
      elevation: 4251,
      lat: -25.7045001984,
      lon: 26.9090003967,
      tz: "Africa/Johannesburg",
    },
    FAMT: {
      icao: "FAMT",
      iata: "",
      name: "Molteno Airport",
      city: "Molteno",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 5254,
      lat: -31.3896007538,
      lon: 26.348400116,
      tz: "Africa/Johannesburg",
    },
    FAMU: {
      icao: "FAMU",
      iata: "MZQ",
      name: "Mkuze Airport",
      city: "Mkuze",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 400,
      lat: -27.6261005402,
      lon: 32.0443000793,
      tz: "Africa/Johannesburg",
    },
    FAMV: {
      icao: "FAMV",
      iata: "",
      name: "Montrose Airport",
      city: "Montrose",
      state: "Limpopo",
      country: "ZA",
      elevation: 2690,
      lat: -24.625,
      lon: 30.1861114502,
      tz: "Africa/Johannesburg",
    },
    FAMX: {
      icao: "FAMX",
      iata: "",
      name: "Mbazwana Airport",
      city: "Mbazwana",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 195,
      lat: -27.4813995361,
      lon: 32.5938987732,
      tz: "Africa/Johannesburg",
    },
    FAMY: {
      icao: "FAMY",
      iata: "",
      name: "Malmesbury Airport",
      city: "Mammesbury",
      state: "Western-Cape",
      country: "ZA",
      elevation: 971,
      lat: -33.4618988037,
      lon: 18.700799942,
      tz: "Africa/Johannesburg",
    },
    FAMZ: {
      icao: "FAMZ",
      iata: "",
      name: "Msauli Airport",
      city: "Msauli",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 2548,
      lat: -26.0499992371,
      lon: 31.0170001984,
      tz: "Africa/Johannesburg",
    },
    FANA: {
      icao: "FANA",
      iata: "",
      name: "Nongoma Airport",
      city: "Nongoma",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2596,
      lat: -27.9139995575,
      lon: 31.6562004089,
      tz: "Africa/Johannesburg",
    },
    FANC: {
      icao: "FANC",
      iata: "NCS",
      name: "Newcastle Airport",
      city: "Newcastle",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4074,
      lat: -27.7705993652,
      lon: 29.9769001007,
      tz: "Africa/Johannesburg",
    },
    FANG: {
      icao: "FANG",
      iata: "NGL",
      name: "Ngala Airport",
      city: "Ngala",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 3357,
      lat: -24.3878002167,
      lon: 31.325799942,
      tz: "Africa/Johannesburg",
    },
    FANH: {
      icao: "FANH",
      iata: "",
      name: "New Hanover Airport",
      city: "New Hanover",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2490,
      lat: -29.3560009003,
      lon: 30.5184001923,
      tz: "Africa/Johannesburg",
    },
    FANL: {
      icao: "FANL",
      iata: "",
      name: "New Largo Airport",
      city: "Witbank",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5038,
      lat: -25.9785003662,
      lon: 28.9843997955,
      tz: "Africa/Johannesburg",
    },
    FANS: {
      icao: "FANS",
      iata: "NLP",
      name: "Nelspruit Airport",
      city: "Nelspruit",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 2875,
      lat: -25.5,
      lon: 30.9137992859,
      tz: "Africa/Johannesburg",
    },
    FANV: {
      icao: "FANV",
      iata: "",
      name: "Nieuwoudtville Airfield",
      city: "Nieuwoudtville",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 1890,
      lat: -31.3500003815,
      lon: 19.1166667938,
      tz: "Africa/Johannesburg",
    },
    FANY: {
      icao: "FANY",
      iata: "",
      name: "Nylstroom Airfield",
      city: "Modimolle",
      state: "Limpopo",
      country: "ZA",
      elevation: 3900,
      lat: -24.6861000061,
      lon: 28.4349002838,
      tz: "Africa/Johannesburg",
    },
    FAOB: {
      icao: "FAOB",
      iata: "OVG",
      name: "Overberg Airport",
      city: "Overberg",
      state: "Western-Cape",
      country: "ZA",
      elevation: 52,
      lat: -34.554901123,
      lon: 20.2506999969,
      tz: "Africa/Johannesburg",
    },
    FAOD: {
      icao: "FAOD",
      iata: "",
      name: "Odendaalsrus Airport",
      city: "Odendaalsrus",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 1340,
      lat: -27.8710002899,
      lon: 26.6933994293,
      tz: "Africa/Johannesburg",
    },
    FAOF: {
      icao: "FAOF",
      iata: "",
      name: "Jack Duvenhage Airport",
      city: "Olifantshoek",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4216,
      lat: -27.9617004395,
      lon: 22.7166004181,
      tz: "Africa/Johannesburg",
    },
    FAOH: {
      icao: "FAOH",
      iata: "OUH",
      name: "Oudtshoorn Airport",
      city: "Oudtshoorn",
      state: "Western-Cape",
      country: "ZA",
      elevation: 1063,
      lat: -33.6069984436,
      lon: 22.188999176,
      tz: "Africa/Johannesburg",
    },
    FAOI: {
      icao: "FAOI",
      iata: "",
      name: "Orient Glider Airport",
      city: "Orient",
      state: "Gauteng",
      country: "ZA",
      elevation: 5102,
      lat: -26.0394001007,
      lon: 27.5956001282,
      tz: "Africa/Johannesburg",
    },
    FAOL: {
      icao: "FAOL",
      iata: "",
      name: "Othawa Airport",
      city: "Otthawa",
      state: "Limpopo",
      country: "ZA",
      elevation: 1098,
      lat: -24.7329998016,
      lon: 31.3999996185,
      tz: "Africa/Johannesburg",
    },
    FAON: {
      icao: "FAON",
      iata: "",
      name: "Ornate Lake St L Airport",
      city: "Hluhluwe",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 59,
      lat: -28.0449008942,
      lon: 32.4253997803,
      tz: "Africa/Johannesburg",
    },
    FAOR: {
      icao: "FAOR",
      iata: "JNB",
      name: "O. R. Tambo International Airport",
      city: "Johannesburg",
      state: "Gauteng",
      country: "ZA",
      elevation: 5558,
      lat: -26.133333,
      lon: 28.25,
      tz: "Africa/Johannesburg",
    },
    FAOT: {
      icao: "FAOT",
      iata: "",
      name: "Ottosdal Airport",
      city: "Ottosdal",
      state: "North-West",
      country: "ZA",
      elevation: 4860,
      lat: -26.7982997894,
      lon: 26.0002994537,
      tz: "Africa/Johannesburg",
    },
    FAOY: {
      icao: "FAOY",
      iata: "",
      name: "Orkney Airport",
      city: "Orkney",
      state: "North-West",
      country: "ZA",
      elevation: 4265,
      lat: -26.9839000702,
      lon: 26.6513996124,
      tz: "Africa/Johannesburg",
    },
    FAPA: {
      icao: "FAPA",
      iata: "AFD",
      name: "Port Alfred Airport",
      city: "Port Alfred",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 307,
      lat: -33.5541992188,
      lon: 26.8777008057,
      tz: "Africa/Johannesburg",
    },
    FAPC: {
      icao: "FAPC",
      iata: "",
      name: "Prince Albert Airport",
      city: "Prince Albert",
      state: "Western-Cape",
      country: "ZA",
      elevation: 2001,
      lat: -33.2024993896,
      lon: 22.0321998596,
      tz: "Africa/Johannesburg",
    },
    FAPD: {
      icao: "FAPD",
      iata: "",
      name: "Pofadder Airport",
      city: "Pofadder",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3241,
      lat: -29.1417007446,
      lon: 19.4130992889,
      tz: "Africa/Johannesburg",
    },
    FAPE: {
      icao: "FAPE",
      iata: "PLZ",
      name: "Port Elizabeth Airport",
      city: "Port Elizabeth",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 226,
      lat: -33.9849014282,
      lon: 25.6173000336,
      tz: "Africa/Johannesburg",
    },
    FAPF: {
      icao: "FAPF",
      iata: "",
      name: "Piet Retief Airport",
      city: "Piet Retief",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 4423,
      lat: -26.9969005585,
      lon: 30.8407993317,
      tz: "Africa/Johannesburg",
    },
    FAPG: {
      icao: "FAPG",
      iata: "PBZ",
      name: "Plettenberg Bay Airport",
      city: "Plettenberg Bay",
      state: "Western-Cape",
      country: "ZA",
      elevation: 465,
      lat: -34.0903015137,
      lon: 23.3278007507,
      tz: "Africa/Johannesburg",
    },
    FAPH: {
      icao: "FAPH",
      iata: "PHW",
      name: "Hendrik Van Eck Airport",
      city: "Phalaborwa",
      state: "Limpopo",
      country: "ZA",
      elevation: 1432,
      lat: -23.9372005463,
      lon: 31.1553993225,
      tz: "Africa/Johannesburg",
    },
    FAPI: {
      icao: "FAPI",
      iata: "",
      name: "Pietersburg Municipal Airport",
      city: "Polokwane",
      state: "Limpopo",
      country: "ZA",
      elevation: 4354,
      lat: -23.9260997772,
      lon: 29.4843997955,
      tz: "Africa/Johannesburg",
    },
    FAPJ: {
      icao: "FAPJ",
      iata: "JOH",
      name: "Port St Johns Airport",
      city: "Port St Johns",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 1227,
      lat: -31.6058998108,
      lon: 29.5198001862,
      tz: "Africa/Johannesburg",
    },
    FAPK: {
      icao: "FAPK",
      iata: "PRK",
      name: "Prieska Airport",
      city: "Prieska",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3100,
      lat: -29.683599472,
      lon: 22.7705993652,
      tz: "Africa/Johannesburg",
    },
    FAPL: {
      icao: "FAPL",
      iata: "",
      name: "Pongola Airport",
      city: "Pongola",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 942,
      lat: -27.3621997833,
      lon: 31.6067008972,
      tz: "Africa/Johannesburg",
    },
    FAPM: {
      icao: "FAPM",
      iata: "PZB",
      name: "Pietermaritzburg Airport",
      city: "Pietermaritzburg",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 2423,
      lat: -29.6490001678,
      lon: 30.3987007141,
      tz: "Africa/Johannesburg",
    },
    FAPN: {
      icao: "FAPN",
      iata: "NTY",
      name: "Pilanesberg International Airport",
      city: "Pilanesberg",
      state: "North-West",
      country: "ZA",
      elevation: 3412,
      lat: -25.3337993622,
      lon: 27.1734008789,
      tz: "Africa/Johannesburg",
    },
    FAPO: {
      icao: "FAPO",
      iata: "",
      name: "Pilgrims Rest Airport",
      city: "Mankolehlotlo",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 3802,
      lat: -24.7847003937,
      lon: 30.7922000885,
      tz: "Africa/Johannesburg",
    },
    FAPP: {
      icao: "FAPP",
      iata: "PTG",
      name: "Polokwane International Airport",
      city: "Potgietersrus",
      state: "Limpopo",
      country: "ZA",
      elevation: 4076,
      lat: -23.8453006744,
      lon: 29.4585990906,
      tz: "Africa/Johannesburg",
    },
    FAPQ: {
      icao: "FAPQ",
      iata: "",
      name: "Punda Maria(Malia) Airport",
      city: "Kruger National Park",
      state: "Limpopo",
      country: "ZA",
      elevation: 1500,
      lat: -22.77,
      lon: 31.0108,
      tz: "Africa/Johannesburg",
    },
    FAPS: {
      icao: "FAPS",
      iata: "PCF",
      name: "Potchefstroom Airport",
      city: "Potchefstroom",
      state: "North-West",
      country: "ZA",
      elevation: 4520,
      lat: -26.670999527,
      lon: 27.0818996429,
      tz: "Africa/Johannesburg",
    },
    FAPT: {
      icao: "FAPT",
      iata: "",
      name: "Posmasburg Soil Airport",
      city: "Postmasburg",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4301,
      lat: -28.3386001587,
      lon: 23.07970047,
      tz: "Africa/Johannesburg",
    },
    FAPU: {
      icao: "FAPU",
      iata: "",
      name: "Paarl East Airport",
      city: "Paarl",
      state: "Western-Cape",
      country: "ZA",
      elevation: 596,
      lat: -33.7107666667,
      lon: 19.0243888889,
      tz: "Africa/Johannesburg",
    },
    FAPV: {
      icao: "FAPV",
      iata: "",
      name: "Petrusville Airport",
      city: "Petrusville",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4116,
      lat: -30.0818004608,
      lon: 24.679599762,
      tz: "Africa/Johannesburg",
    },
    FAPW: {
      icao: "FAPW",
      iata: "",
      name: "Pietersrus Airport",
      city: "Pietersrus",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5472,
      lat: -26.6061000824,
      lon: 29.3292007446,
      tz: "Africa/Johannesburg",
    },
    FAPX: {
      icao: "FAPX",
      iata: "",
      name: "Paradise Beach Airport",
      city: "Jeffreysbaal",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 15,
      lat: -34.1027793884,
      lon: 24.8827781677,
      tz: "Africa/Johannesburg",
    },
    FAPY: {
      icao: "FAPY",
      iata: "",
      name: "Parys Airport",
      city: "Parys",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4740,
      lat: -26.8892993927,
      lon: 27.5034008026,
      tz: "Africa/Johannesburg",
    },
    FAPZ: {
      icao: "FAPZ",
      iata: "",
      name: "Progress Airport",
      city: "Sunlands",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 748,
      lat: -33.9300003052,
      lon: 25.3700008392,
      tz: "Africa/Johannesburg",
    },
    FAQF: {
      icao: "FAQF",
      iata: "",
      name: "Pomfret Airport",
      city: "Pomfret",
      state: "North-West",
      country: "ZA",
      elevation: 3817,
      lat: -25.847700119,
      lon: 23.5373001099,
      tz: "Africa/Johannesburg",
    },
    FAQR: {
      icao: "FAQR",
      iata: "",
      name: "Potgietersrus Airport",
      city: "Potgietersus",
      state: "Limpopo",
      country: "ZA",
      elevation: 3500,
      lat: -24.2333335876,
      lon: 28.9833335876,
      tz: "Africa/Johannesburg",
    },
    FAQT: {
      icao: "FAQT",
      iata: "UTW",
      name: "Queenstown Airport",
      city: "Queenstown",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 3637,
      lat: -31.9202003479,
      lon: 26.8822002411,
      tz: "Africa/Johannesburg",
    },
    FARA: {
      icao: "FARA",
      iata: "",
      name: "Petit Airport",
      city: "Daveyton",
      state: "Gauteng",
      country: "ZA",
      elevation: 5460,
      lat: -26.0816669464,
      lon: 28.3999996185,
      tz: "Africa/Johannesburg",
    },
    FARB: {
      icao: "FARB",
      iata: "RCB",
      name: "Richards Bay Airport",
      city: "Richards Bay",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 109,
      lat: -28.7409992218,
      lon: 32.0920982361,
      tz: "Africa/Johannesburg",
    },
    FARD: {
      icao: "FARD",
      iata: "",
      name: "Riversdale Airport",
      city: "Riversdale",
      state: "Western-Cape",
      country: "ZA",
      elevation: 591,
      lat: -34.1116981506,
      lon: 21.2628002167,
      tz: "Africa/Johannesburg",
    },
    FARG: {
      icao: "FARG",
      iata: "",
      name: "Rustenburg Airport",
      city: "Rustenburg",
      state: "North-West",
      country: "ZA",
      elevation: 3700,
      lat: -25.6443004608,
      lon: 27.2710990906,
      tz: "Africa/Johannesburg",
    },
    FARI: {
      icao: "FARI",
      iata: "RVO",
      name: "Reivilo Airport",
      city: "Reivilo",
      state: "North-West",
      country: "ZA",
      elevation: 4715,
      lat: -27.5471992493,
      lon: 24.1725006104,
      tz: "Africa/Johannesburg",
    },
    FARM: {
      icao: "FARM",
      iata: "",
      name: "Richmond Airport",
      city: "Richmond",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4731,
      lat: -31.423500061,
      lon: 23.9782009125,
      tz: "Africa/Johannesburg",
    },
    FARO: {
      icao: "FARO",
      iata: "",
      name: "Rooiberg Airport",
      city: "Rooiberg",
      state: "Limpopo",
      country: "ZA",
      elevation: 3811,
      lat: -24.7666664124,
      lon: 27.75,
      tz: "Africa/Johannesburg",
    },
    FARS: {
      icao: "FARS",
      iata: "ROD",
      name: "Robertson Airport",
      city: "Robertson",
      state: "Western-Cape",
      country: "ZA",
      elevation: 640,
      lat: -33.8121986389,
      lon: 19.9027996063,
      tz: "Africa/Johannesburg",
    },
    FARZ: {
      icao: "FARZ",
      iata: "",
      name: "Reitz Airport",
      city: "Maasstroom",
      state: "Limpopo",
      country: "ZA",
      elevation: 5331,
      lat: -22.7842006683,
      lon: 28.4302997589,
      tz: "Africa/Johannesburg",
    },
    FASA: {
      icao: "FASA",
      iata: "",
      name: "Sani Pass Airport",
      city: "Sani Pass",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 5933,
      lat: -29.6571998596,
      lon: 29.4477005005,
      tz: "Africa/Johannesburg",
    },
    FASB: {
      icao: "FASB",
      iata: "SBU",
      name: "Springbok Airport",
      city: "Springbok",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2690,
      lat: -29.6893005371,
      lon: 17.9395999908,
      tz: "Africa/Johannesburg",
    },
    FASC: {
      icao: "FASC",
      iata: "ZEC",
      name: "Secunda Airport",
      city: "Secunda",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5250,
      lat: -26.52409935,
      lon: 29.1700992584,
      tz: "Africa/Johannesburg",
    },
    FASD: {
      icao: "FASD",
      iata: "",
      name: "Saldanha /Vredenburg Airport",
      city: "Saldanha-Vredenburg",
      state: "Western-Cape",
      country: "ZA",
      elevation: 50,
      lat: -32.964099884,
      lon: 17.9692993164,
      tz: "Africa/Johannesburg",
    },
    FASE: {
      icao: "FASE",
      iata: "GSS",
      name: "Sabi Sabi Airport",
      city: "Belfast",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1276,
      lat: -24.9414997101,
      lon: 31.4445991516,
      tz: "Africa/Johannesburg",
    },
    FASG: {
      icao: "FASG",
      iata: "",
      name: "Schweizer Reneke Airport",
      city: "Schweizer Reneke",
      state: "North-West",
      country: "ZA",
      elevation: 4373,
      lat: -27.1630992889,
      lon: 25.2861003876,
      tz: "Africa/Johannesburg",
    },
    FASH: {
      icao: "FASH",
      iata: "",
      name: "Stellenbosch Airport",
      city: "Stellenbosch",
      state: "Western-Cape",
      country: "ZA",
      elevation: 295,
      lat: -33.9799995422,
      lon: 18.8199996948,
      tz: "Africa/Johannesburg",
    },
    FASI: {
      icao: "FASI",
      iata: "",
      name: "Springs Airfield",
      city: "Springs",
      state: "Gauteng",
      country: "ZA",
      elevation: 5340,
      lat: -26.2483997345,
      lon: 28.3974990845,
      tz: "Africa/Johannesburg",
    },
    FASJ: {
      icao: "FASJ",
      iata: "",
      name: "Saffier Airport",
      city: "Saffier",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4700,
      lat: -26.7600002289,
      lon: 27.7600002289,
      tz: "Africa/Johannesburg",
    },
    FASK: {
      icao: "FASK",
      iata: "",
      name: "Swartkop Air Force Base",
      city: "Pretoria",
      state: "Gauteng",
      country: "ZA",
      elevation: 4780,
      lat: -25.8097000122,
      lon: 28.1646003723,
      tz: "Africa/Johannesburg",
    },
    FASL: {
      icao: "FASL",
      iata: "",
      name: "Sutherland Airport",
      city: "Sutherland",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 5247,
      lat: -32.4882011414,
      lon: 20.6970996857,
      tz: "Africa/Johannesburg",
    },
    FASM: {
      icao: "FASM",
      iata: "",
      name: "Siteka Airport",
      city: "Siteka",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4400,
      lat: -29.3250007629,
      lon: 30.1492004395,
      tz: "Africa/Johannesburg",
    },
    FASN: {
      icao: "FASN",
      iata: "",
      name: "Senekal Airport",
      city: "Senekal",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4849,
      lat: -28.3122005463,
      lon: 27.6460990906,
      tz: "Africa/Johannesburg",
    },
    FASR: {
      icao: "FASR",
      iata: "",
      name: "Standerton Airport",
      city: "Standerton",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5200,
      lat: -26.9270000458,
      lon: 29.2099990845,
      tz: "Africa/Johannesburg",
    },
    FASS: {
      icao: "FASS",
      iata: "SIS",
      name: "Sishen Airport",
      city: "Sishen",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3848,
      lat: -27.6485996246,
      lon: 22.9993000031,
      tz: "Africa/Johannesburg",
    },
    FAST: {
      icao: "FAST",
      iata: "",
      name: "Somerset East Airport",
      city: "Somerset East",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2349,
      lat: -32.7501983643,
      lon: 25.5949993134,
      tz: "Africa/Johannesburg",
    },
    FASU: {
      icao: "FASU",
      iata: "",
      name: "Sace Airport",
      city: "Sace",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5151,
      lat: -25.9568996429,
      lon: 29.2117004395,
      tz: "Africa/Johannesburg",
    },
    FASW: {
      icao: "FASW",
      iata: "",
      name: "Slurry Airport",
      city: "Slurry",
      state: "North-West",
      country: "ZA",
      elevation: 4692,
      lat: -25.8155994415,
      lon: 25.8864002228,
      tz: "Africa/Johannesburg",
    },
    FASX: {
      icao: "FASX",
      iata: "",
      name: "Hendrik Swellengrebel Airport",
      city: "Swellendam",
      state: "Western-Cape",
      country: "ZA",
      elevation: 407,
      lat: -34.0481987,
      lon: 20.4745998383,
      tz: "Africa/Johannesburg",
    },
    FASY: {
      icao: "FASY",
      iata: "",
      name: "Syferfontein Airport",
      city: "Hiltonia",
      state: "Gauteng",
      country: "ZA",
      elevation: 5420,
      lat: -26.349199295,
      lon: 27.7793998718,
      tz: "Africa/Johannesburg",
    },
    FASZ: {
      icao: "FASZ",
      iata: "SZK",
      name: "Skukuza Airport",
      city: "Skukuza",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1020,
      lat: -24.960899353,
      lon: 31.5886993408,
      tz: "Africa/Johannesburg",
    },
    FATA: {
      icao: "FATA",
      iata: "",
      name: "Tedderfield Air Park",
      city: "Tedderfield",
      state: "Gauteng",
      country: "ZA",
      elevation: 5198,
      lat: -26.3519992828,
      lon: 27.9689998627,
      tz: "Africa/Johannesburg",
    },
    FATB: {
      icao: "FATB",
      iata: "",
      name: "Thorny Bush Game Lodge Airport",
      city: "Hoedspruit",
      state: "Limpopo",
      country: "ZA",
      elevation: 1900,
      lat: -24.4147224426,
      lon: 31.1650009155,
      tz: "Africa/Johannesburg",
    },
    FATD: {
      icao: "FATD",
      iata: "TDT",
      name: "Tanda Tula Airport",
      city: "Welverdiend",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1555,
      lat: -24.5335998535,
      lon: 31.2999992371,
      tz: "Africa/Johannesburg",
    },
    FATF: {
      icao: "FATF",
      iata: "",
      name: "Tommys Field Airport",
      city: "Beeshoek",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4360,
      lat: -28.2600002289,
      lon: 22.9932003021,
      tz: "Africa/Johannesburg",
    },
    FATH: {
      icao: "FATH",
      iata: "THY",
      name: "Thohoyandou Airport",
      city: "Thohoyandou",
      state: "Limpopo",
      country: "ZA",
      elevation: 2021,
      lat: -23.0769004822,
      lon: 30.383600235,
      tz: "Africa/Johannesburg",
    },
    FATI: {
      icao: "FATI",
      iata: "",
      name: "Thabazimbi Airport",
      city: "Thabazimbi",
      state: "Limpopo",
      country: "ZA",
      elevation: 3225,
      lat: -24.5760850299,
      lon: 27.4196863174,
      tz: "Africa/Johannesburg",
    },
    FATK: {
      icao: "FATK",
      iata: "",
      name: "Tsitsikama Fly Airport",
      city: "Tsitsikama",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 381,
      lat: -34.0847015381,
      lon: 24.2896995544,
      tz: "Africa/Johannesburg",
    },
    FATM: {
      icao: "FATM",
      iata: "",
      name: "Stutterheim Airport",
      city: "Stutterheim",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2675,
      lat: -32.5666656494,
      lon: 27.4500007629,
      tz: "Africa/Johannesburg",
    },
    FATN: {
      icao: "FATN",
      iata: "TCU",
      name: "Thaba Nchu Tar Airport",
      city: "Homeward",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4941,
      lat: -29.3178005219,
      lon: 26.8227996826,
      tz: "Africa/Johannesburg",
    },
    FATP: {
      icao: "FATP",
      iata: "",
      name: "New Tempe Airport",
      city: "Bain's Vlei",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4547,
      lat: -29.0328998566,
      lon: 26.1576004028,
      tz: "Africa/Johannesburg",
    },
    FATR: {
      icao: "FATR",
      iata: "",
      name: "Trennery's Airport",
      city: "Qolora",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 114,
      lat: -32.6385993958,
      lon: 28.4242992401,
      tz: "Africa/Johannesburg",
    },
    FATT: {
      icao: "FATT",
      iata: "",
      name: "Tutuka Power Station Airport",
      city: "Standerton",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5313,
      lat: -26.776599884,
      lon: 29.3388004303,
      tz: "Africa/Johannesburg",
    },
    FATW: {
      icao: "FATW",
      iata: "",
      name: "Witberg Tswalu Airport",
      city: "Tswalo Game Reserve",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3921,
      lat: -27.2049999237,
      lon: 22.4818992615,
      tz: "Africa/Johannesburg",
    },
    FATZ: {
      icao: "FATZ",
      iata: "LTA",
      name: "Tzaneen Airport",
      city: "Tzaneen",
      state: "Limpopo",
      country: "ZA",
      elevation: 1914,
      lat: -23.8243999481,
      lon: 30.3292999268,
      tz: "Africa/Johannesburg",
    },
    FAUB: {
      icao: "FAUB",
      iata: "",
      name: "Underberg Airport",
      city: "Underberg",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 5057,
      lat: -29.78840065,
      lon: 29.4983005524,
      tz: "Africa/Johannesburg",
    },
    FAUC: {
      icao: "FAUC",
      iata: "",
      name: "Ulco Airport",
      city: "Ulco",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3512,
      lat: -28.3544998169,
      lon: 24.2290992737,
      tz: "Africa/Johannesburg",
    },
    FAUG: {
      icao: "FAUG",
      iata: "",
      name: "Ugie Airport",
      city: "Ugie",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 4580,
      lat: -31.2199993134,
      lon: 28.2099990845,
      tz: "Africa/Johannesburg",
    },
    FAUH: {
      icao: "FAUH",
      iata: "",
      name: "Uitenhage Airport",
      city: "Uitenhage",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 289,
      lat: -33.7853012085,
      lon: 25.3833007813,
      tz: "Africa/Johannesburg",
    },
    FAUL: {
      icao: "FAUL",
      iata: "ULD",
      name: "Prince Mangosuthu Buthelezi Airport",
      city: "Ulundi",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 1720,
      lat: -28.3206005096,
      lon: 31.4165000916,
      tz: "Africa/Johannesburg",
    },
    FAUP: {
      icao: "FAUP",
      iata: "UTN",
      name: "Pierre Van Ryneveld Airport",
      city: "Upington",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 2782,
      lat: -28.39909935,
      lon: 21.2602005005,
      tz: "Africa/Johannesburg",
    },
    FAUR: {
      icao: "FAUR",
      iata: "",
      name: "Utrecht Airport",
      city: "Utrecht",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 4101,
      lat: -27.6805000305,
      lon: 30.3167991638,
      tz: "Africa/Johannesburg",
    },
    FAUS: {
      icao: "FAUS",
      iata: "ULX",
      name: "Ulusaba Airport",
      city: "Ulusaba",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 1263,
      lat: -24.7854003906,
      lon: 31.3549003601,
      tz: "Africa/Johannesburg",
    },
    FAUT: {
      icao: "FAUT",
      iata: "UTT",
      name: "K. D. Matanzima Airport",
      city: "Mthatha",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2400,
      lat: -31.5478992462,
      lon: 28.6742992401,
      tz: "Africa/Johannesburg",
    },
    FAVA: {
      icao: "FAVA",
      iata: "",
      name: "Vaalputs Airport",
      city: "Vaalputs",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3340,
      lat: -30.1341991425,
      lon: 18.5266990662,
      tz: "Africa/Johannesburg",
    },
    FAVB: {
      icao: "FAVB",
      iata: "VRU",
      name: "Vryburg Airport",
      city: "Vyrburg",
      state: "North-West",
      country: "ZA",
      elevation: 3920,
      lat: -26.9824008942,
      lon: 24.7287998199,
      tz: "Africa/Johannesburg",
    },
    FAVD: {
      icao: "FAVD",
      iata: "",
      name: "Vrede Airport",
      city: "Vrede",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 5499,
      lat: -27.4402999878,
      lon: 29.1530990601,
      tz: "Africa/Johannesburg",
    },
    FAVE: {
      icao: "FAVE",
      iata: "",
      name: "Ventersdorp Airport",
      city: "Ventersdorp",
      state: "North-West",
      country: "ZA",
      elevation: 4917,
      lat: -26.3008995056,
      lon: 26.8141994476,
      tz: "Africa/Johannesburg",
    },
    FAVF: {
      icao: "FAVF",
      iata: "",
      name: "Verborgenfontei Airport",
      city: "Verborgenfontein",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4360,
      lat: -31.1658000946,
      lon: 23.8094005585,
      tz: "Africa/Johannesburg",
    },
    FAVG: {
      icao: "FAVG",
      iata: "VIR",
      name: "Virginia Airport",
      city: "Durban",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 20,
      lat: -29.7705993652,
      lon: 31.0583992004,
      tz: "Africa/Johannesburg",
    },
    FAVI: {
      icao: "FAVI",
      iata: "",
      name: "Von Abo's Villa Airport",
      city: "Von Abo's Villa",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4304,
      lat: -27.6105995178,
      lon: 26.6835002899,
      tz: "Africa/Johannesburg",
    },
    FAVM: {
      icao: "FAVM",
      iata: "",
      name: "Venetia Airport",
      city: "Venetia Mine",
      state: "Limpopo",
      country: "ZA",
      elevation: 2333,
      lat: -22.4480991364,
      lon: 29.3376998901,
      tz: "Africa/Johannesburg",
    },
    FAVP: {
      icao: "FAVP",
      iata: "",
      name: "Vanderbijlpark Airport",
      city: "Vanderbijlpark",
      state: "Gauteng",
      country: "ZA",
      elevation: 4861,
      lat: -26.6902999878,
      lon: 27.7770996094,
      tz: "Africa/Johannesburg",
    },
    FAVR: {
      icao: "FAVR",
      iata: "VRE",
      name: "Vredendal Airport",
      city: "Vredendal",
      state: "Western-Cape",
      country: "ZA",
      elevation: 330,
      lat: -31.6410007477,
      lon: 18.5447998047,
      tz: "Africa/Johannesburg",
    },
    FAVS: {
      icao: "FAVS",
      iata: "",
      name: "Vastrap Airport",
      city: "Upington",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3245,
      lat: -27.8413887024,
      lon: 21.6341667175,
      tz: "Africa/Johannesburg",
    },
    FAVU: {
      icao: "FAVU",
      iata: "",
      name: "Volksrust Airport",
      city: "Volksrust",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 5610,
      lat: -27.3768997192,
      lon: 29.8600006104,
      tz: "Africa/Johannesburg",
    },
    FAVV: {
      icao: "FAVV",
      iata: "",
      name: "Vereeniging Airport",
      city: "Vereeniging",
      state: "Gauteng",
      country: "ZA",
      elevation: 4846,
      lat: -26.566400528,
      lon: 27.9608001709,
      tz: "Africa/Johannesburg",
    },
    FAVW: {
      icao: "FAVW",
      iata: "",
      name: "Victoria West Airport",
      city: "Victoria West",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 4124,
      lat: -31.3994007111,
      lon: 23.1564006805,
      tz: "Africa/Johannesburg",
    },
    FAVY: {
      icao: "FAVY",
      iata: "VYD",
      name: "Vryheid Airport",
      city: "Vryheid",
      state: "KwaZulu-Natal",
      country: "ZA",
      elevation: 3799,
      lat: -27.7868995667,
      lon: 30.7964000702,
      tz: "Africa/Johannesburg",
    },
    FAWA: {
      icao: "FAWA",
      iata: "",
      name: "Warmbaths Airport",
      city: "Warmbaths",
      state: "Limpopo",
      country: "ZA",
      elevation: 3655,
      lat: -24.9099998474,
      lon: 28.2999992371,
      tz: "Africa/Johannesburg",
    },
    FAWB: {
      icao: "FAWB",
      iata: "PRY",
      name: "Wonderboom Airport",
      city: "Pretoria",
      state: "Gauteng",
      country: "ZA",
      elevation: 4095,
      lat: -25.6539001465,
      lon: 28.224199295,
      tz: "Africa/Johannesburg",
    },
    FAWC: {
      icao: "FAWC",
      iata: "",
      name: "Worcester Glider Airport",
      city: "Worcester",
      state: "Western-Cape",
      country: "ZA",
      elevation: 673,
      lat: -33.6631011963,
      lon: 19.4153003693,
      tz: "Africa/Johannesburg",
    },
    FAWD: {
      icao: "FAWD",
      iata: "",
      name: "Wolmeransstad Airport",
      city: "Wolmeransstad",
      state: "North-West",
      country: "ZA",
      elevation: 4513,
      lat: -27.1700000763,
      lon: 25.9799995422,
      tz: "Africa/Johannesburg",
    },
    FAWI: {
      icao: "FAWI",
      iata: "",
      name: "Witbank Airport",
      city: "Witbank",
      state: "Mpumalanga",
      country: "ZA",
      elevation: 5078,
      lat: -25.8323001862,
      lon: 29.1919994354,
      tz: "Africa/Johannesburg",
    },
    FAWK: {
      icao: "FAWK",
      iata: "WKF",
      name: "Waterkloof Air Force Base",
      city: "Pretoria",
      state: "Gauteng",
      country: "ZA",
      elevation: 4940,
      lat: -25.8299999237,
      lon: 28.2224998474,
      tz: "Africa/Johannesburg",
    },
    FAWL: {
      icao: "FAWL",
      iata: "",
      name: "Williston Airport",
      city: "Williston",
      state: "Northern-Cape",
      country: "ZA",
      elevation: 3484,
      lat: -31.383600235,
      lon: 20.932800293,
      tz: "Africa/Johannesburg",
    },
    FAWM: {
      icao: "FAWM",
      iata: "WEL",
      name: "Welkom Airport",
      city: "Welkom",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4399,
      lat: -27.9979991913,
      lon: 26.6695995331,
      tz: "Africa/Johannesburg",
    },
    FAWN: {
      icao: "FAWN",
      iata: "",
      name: "Winburg Airport",
      city: "Winburg",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4800,
      lat: -28.5,
      lon: 27.0166664124,
      tz: "Africa/Johannesburg",
    },
    FAWO: {
      icao: "FAWO",
      iata: "",
      name: "Willowmore Airport",
      city: "Willowmore",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 2608,
      lat: -33.2633018494,
      lon: 23.4906005859,
      tz: "Africa/Johannesburg",
    },
    FAWP: {
      icao: "FAWP",
      iata: "",
      name: "Wepener Airport",
      city: "Wepener",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4755,
      lat: -29.7423992157,
      lon: 27.022600174,
      tz: "Africa/Johannesburg",
    },
    FAWR: {
      icao: "FAWR",
      iata: "",
      name: "Wavecrest Airport",
      city: "Wavecrest",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 89,
      lat: -32.5896987915,
      lon: 28.5191993713,
      tz: "Africa/Johannesburg",
    },
    FAWS: {
      icao: "FAWS",
      iata: "",
      name: "Wesselbronn Af Airport",
      city: "Wesselsbron",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4301,
      lat: -27.8467006683,
      lon: 26.3505992889,
      tz: "Africa/Johannesburg",
    },
    FAWT: {
      icao: "FAWT",
      iata: "",
      name: "Winterveldt Mine Airport",
      city: "Doornbosch",
      state: "Limpopo",
      country: "ZA",
      elevation: 3000,
      lat: -24.665,
      lon: 30.18528,
      tz: "Africa/Johannesburg",
    },
    FAYP: {
      icao: "FAYP",
      iata: "",
      name: "Ysterplaat Air Force Base",
      city: "Cape Town",
      state: "Western-Cape",
      country: "ZA",
      elevation: 52,
      lat: -33.9001998901,
      lon: 18.4983005524,
      tz: "Africa/Johannesburg",
    },
    FAZA: {
      icao: "FAZA",
      iata: "",
      name: "Zastron Airport",
      city: "Zastron",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4265,
      lat: -30.2999992371,
      lon: 27.1170005798,
      tz: "Africa/Johannesburg",
    },
    FAZP: {
      icao: "FAZP",
      iata: "",
      name: "Mazeppa Bay Airport",
      city: "Mazeppa Bay",
      state: "Eastern-Cape",
      country: "ZA",
      elevation: 13,
      lat: -32.4719009399,
      lon: 28.6527996063,
      tz: "Africa/Johannesburg",
    },
    FAZQ: {
      icao: "FAZQ",
      iata: "",
      name: "Star Airport",
      city: "Star",
      state: "Orange-Free-State",
      country: "ZA",
      elevation: 4754,
      lat: -26.8931007385,
      lon: 27.6900005341,
      tz: "Africa/Johannesburg",
    },
    FAZR: {
      icao: "FAZR",
      iata: "",
      name: "Zeerust Airport",
      city: "Zeerust",
      state: "North-West",
      country: "ZA",
      elevation: 4258,
      lat: -25.5990009308,
      lon: 26.0422992706,
      tz: "Africa/Johannesburg",
    },
  },
];

const num = jsonObjectArray[0];
const myArr = [];
for (var prop in num) {
  myArr.push(num[prop]);
}

export const UberContext = createContext();

export const UberProvider = ({ children }) => {
  const [pickup, setPickup] = useState("");
  const [dropoff, setDropoff] = useState("");
  const [pickupCoordinates, setPickupCoordinates] = useState();
  const [dropoffCoordinates, setDropoffCoordinates] = useState();
  const [departAirCoords, setDepartAirCoords] = useState();
  const [arriveAirCoords, setArriveAirCoords] = useState();
  const [currentAccount, setCurrentAccount] = useState();
  const [currentUser, setCurrentUser] = useState([]);
  const [selectedRide, setSelectedRide] = useState([]);
  const [price, setPrice] = useState();
  const [basePrice, setBasePrice] = useState();

  let metamask;

  if (typeof window !== "undefined") {
    metamask = window.ethereum;
  }

  useEffect(() => {
    checkIfWalletIsConnected();
  }, []);

  useEffect(() => {
    if (!currentAccount) return;
    requestToGetCurrentUsersInfo(currentAccount);
  }, [currentAccount]);

  useEffect(() => {
    if (!pickupCoordinates || !dropoffCoordinates) return;
    (async () => {
      try {
        const response = await fetch("/api/map/getDuration", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            pickupCoordinates: `${pickupCoordinates[0]},${pickupCoordinates[1]}`,
            dropoffCoordinates: `${dropoffCoordinates[0]},${dropoffCoordinates[1]}`,
          }),
        });

        const data = await response.json();
        setBasePrice(Math.round(await data.data));
      } catch (error) {
        console.error(error);
      }
    })();
  }, [pickupCoordinates, dropoffCoordinates]);

  const checkIfWalletIsConnected = async () => {
    if (!window.ethereum) return;
    try {
      const addressArray = await window.ethereum.request({
        method: "eth_accounts",
      });

      if (addressArray.length > 0) {
        setCurrentAccount(addressArray[0]);
        requestToCreateUserOnSanity(addressArray[0]);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const connectWallet = async () => {
    if (!window.ethereum) return;
    try {
      const addressArray = await window.ethereum.request({
        method: "eth_requestAccounts",
      });

      if (addressArray.length > 0) {
        setCurrentAccount(addressArray[0]);
        requestToCreateUserOnSanity(addressArray[0]);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const createLocationCoordinatePromise = (locationName, locationType) => {
    return new Promise(async (resolve, reject) => {
      try {
        const response = await fetch("api/map/getLocationCoordinates", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            location: locationName,
          }),
        });

        const data = await response.json();

        if (data.message === "success") {
          switch (locationType) {
            case "pickup":
              console.log("received pickup cords: ", data.data);
              setPickupCoordinates(data.data);
              nearbyDepart(data.data);
              break;
            case "dropoff":
              setDropoffCoordinates(data.data);
              nearbyArrive(data.data);
              break;
          }
          resolve();
        } else {
          reject();
        }
      } catch (error) {
        console.error(error);
        reject();
      }
    });
  };

  useEffect(() => {
    if (pickup && dropoff) {
      (async () => {
        await Promise.all([
          createLocationCoordinatePromise(pickup, "pickup"),
          createLocationCoordinatePromise(dropoff, "dropoff"),
        ]);
      })();
    } else return;
  }, [pickup, dropoff]);

  const maxResults = 1;
  const maxDistance = 20000000;

  const sphereKnn = require("sphere-knn");
  const lookup = sphereKnn(myArr);

  const nearbyDepart = (data) => {
    const points = lookup(data[1], data[0], maxResults, maxDistance);
    const nearestAirportCords = [points[0].lon, points[0].lat];
    setDepartAirCoords(nearestAirportCords);
  };

  const nearbyArrive = (data) => {
    const points = lookup(data[1], data[0], maxResults, maxDistance);
    const nearestAirportCords = [points[0].lon, points[0].lat];
    setArriveAirCoords(nearestAirportCords);
  };

  const requestToCreateUserOnSanity = async (address) => {
    if (!window.ethereum) return;
    try {
      await fetch("/api/db/createUser", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          userWalletAddress: address,
          name: faker.name.findName(),
        }),
      });
    } catch (error) {
      console.error(error);
    }
  };

  const requestToGetCurrentUsersInfo = async (walletAddress) => {
    try {
      const response = await fetch(
        `/api/db/getUserInfo?walletAddress=${walletAddress}`
      );

      const data = await response.json();
      setCurrentUser(data.data);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <UberContext.Provider
      value={{
        pickup,
        setPickup,
        dropoff,
        setDropoff,
        pickupCoordinates,
        setPickupCoordinates,
        dropoffCoordinates,
        setDropoffCoordinates,
        departAirCoords,
        setDepartAirCoords,
        arriveAirCoords,
        setArriveAirCoords,
        connectWallet,
        currentAccount,
        currentUser,
        selectedRide,
        setSelectedRide,
        price,
        setPrice,
        basePrice,
        metamask,
      }}
    >
      {children}
    </UberContext.Provider>
  );
};
